[package]
name = "changevalues"
version = "0.1.0"
edition = "2021"
authors = ["<rickporto.sec@gmail.com>"]

[dependencies]
winreg = "0.51"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1 
panic = "abort"
incremental = false
debug = false
